package shared.transfer;

public enum UserAction
{
  LOGIN_REQUEST,
  LOGIN_REQUEST_MANAGER,
  LOGIN_REQUEST_SECRETARY,
  LOGIN_REQUEST_EMPLOYEE,
  LOGOUT_USER,
  LOGIN_RESULT,
  PRODUCT_LIST,
  SUPPLIER_LIST,
  ADD_NEW_SUPPLIER,
  GET_VALUES_FROM_DAO,
  STAFF_LIST,
  CUSTOMER_LIST,
  CREATE_NEW_EMPLOYEE,
  CREATE_NEW_SECRETARY,
  CREATE_NEW_MANAGER,
  DAMAGED_PRODUCT,
  MOVE_PRODUCT_TO_DAMAGE_LIST,
  USER_LIST,
}


