package shared.transfer;

public enum UserAction
{
  LOGIN_REQUEST,
  LOGIN_REQUEST_MANAGER,
  LOGIN_REQUEST_SECRETARY,
  LOGIN_REQUEST_EMPLOYEE,
  LOGIN_RESULT,
  PRODUCT_LIST,
  SUPPLIER_LIST,
  STAFF_LIST,
  CUSTOMER_LIST,
  MANAGER,
  EMPLOYEE,
  SECRETARY,
  DAMAGED_PRODUCT,
  MOVE_PRODUCT_TO_DAMAGE_LIST,
  USER_LIST,
}


